### ISSUE TITLE
Automatic crawler update check error

### ISSUE THREAD

**Issue by dproudGSA** [GSA/idmanagement.gov#758] opened 2024-01-23 21:36 UTC
**Describe the bug**
I noticed the last couple of weeks that the "Code scanning results / CodeQL" check has an error. It's not a fatal error and the PRs are still able to be merged. The most recent PR is #757. 

When I click on "Details" and look at the "Analyze (javascript-typescript)," there is an error message at line 767 that says, " Warning: Failed to restore: Cache service responded with 403"

I'm not sure if, or how much, of a problem this is. Just thought I'd bring it to your attention.

**Comment by claytonjbarnette** [comment] 2024-01-24 14:26
@dproudGSA @JBPayne007  I will look into it.  👍

**Comment by claytonjbarnette** [comment] 2024-01-24 17:40
@dproudGSA @JBPayne007 

This has an open issue on GitHub [here](https://github.com/actions/cache/issues/319). 

🤔 From what I understand, the cause is related to caching that normally happens on a main branch, but is trying to run on a cloned or development branch, where it has no such caching capabilities. This is why the rest of your build and code analysis succeeds and this error is presented. 

I think we can look past this issue, unless builds start to fail. For now, I would just keep 👀 on it.

**Comment by claytonjbarnette** [comment] 2024-01-30 16:03
Closing this issue, since no other issues are present. 

@JBPayne007 
@dproudGSA 
@SuGhadiali 
@TheInfinityBeyonder

**Closed as completed by claytonjbarnette** 2024-01-30 16:03 UTC
